# Generated by Django 5.0.4 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='Registered Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
